FROM python:3.9-slim

# install some stuff
RUN apt-get update \
    && apt-get install tini \
    && pip install --no-cache-dir prefect[aws, kubernetes] PyGithub dask[complete] s3fs tini 

# Harden Image and Start Agent script
COPY setup.sh /bin/setup.sh
RUN chmod +x /bin/setup.sh
ENV INFRASTRUCTURE=aws


# ENTRYPOINT / RUN
ENTRYPOINT ["/usr/bin/tini", "-s", "-g", "--", "/bin/setup.sh"]